[package]
name = "qiskit-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
operation_macro = { path = "operation_macro" }
ndarray = "0.15.6"
# ndarray-linalg = "0.16.0"
numpy = "0.21"
pyo3 = "0.21.0"
memmap2 = "0.9.4"
regex = "1.10.5"
list-any = "0.2.1"
